kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  namespace: {{.Namespace}}
  name: trainingoperator-servicemonitor
  labels:
    monitoring.opendatahub.io/scrape: "true"
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/part-of: changeme