kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  namespace: {{.Namespace}}
  name: llamastackoperator-servicemonitor
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-stack-k8s-operator